flowchart TB
 E["E: Ekosistem"] -->|Kebutuhan| A["A: Aplikasi"]
 A -->|Persyaratan| S["S: Sistem"]
 S -->|Kemampuan| T["T: Teknologi"]
 T -->|Gap pengetahuan| F["F: Fundamental"]
 F -->|Prinsip| T
 T -->|Komponen| S
 S -->|Layanan| A
 A -->|Manfaat dan dampak| E
